package main

import "fmt"

func main() {
	fmt.Println("---- HELLO WORLD ----")
	helloWorld()
	fmt.Println("---- VALUES ----")
	values()
	fmt.Println("---- VARIABLES ----")
	variables()
	fmt.Println("---- CONSTANTS ----")
	constants()
	fmt.Println("---- FOR LOOPS ----")
	forLoop()
	fmt.Println("---- IF ELSE ----")
	ifelse()
	fmt.Println("---- SWITCH ----")
	switchCase()
	fmt.Println("---- ARRAYS ----")
	arrays()
	fmt.Println("---- SLICES ----")
	slice()
	fmt.Println("---- MAPS ----")
	mapType()
	fmt.Println("---- RANGE ----")
	ranges()
	fmt.Println("---- FUNCTIONS ----")
	functions()
	fmt.Println("---- MULTIPLE RETURN VALUES ----")
	multipleReturns()
	fmt.Println("---- VARIADIC ----")
	variadic()
	fmt.Println("---- CLOSURES ----")
	closures()
	fmt.Println("---- RECURSION ----")
	recursion()
	fmt.Println("---- POINTERS ----")
	pointers()
	fmt.Println("---- RUNES ----")
	runes()
	fmt.Println("---- STRUCTS ----")
	structs()
	fmt.Println("---- METHODS ----")
	methods()
}
